#!/usr/bin/env python3
"""Seed tool dependencies at deploy time.

Scans all mcp_tools/*/meta.json for the 'dependencies' field,
collects Python packages, and either generates a requirements.txt
or installs them directly.

Usage:
    # Generate requirements.txt only
    python scripts/seed_dependencies.py

    # Install directly
    python scripts/seed_dependencies.py --install

    # Install for a specific tool
    python scripts/seed_dependencies.py --install --tool chart_create
"""

import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MCP_TOOLS_DIR = REPO_ROOT / "mcp_tools"
REQUIREMENTS_PATH = REPO_ROOT / "requirements-tools.txt"


def collect_dependencies(tool_filter: str = "") -> dict[str, set[str]]:
    """Scan all tool meta.json files and collect dependencies by language.

    Args:
        tool_filter: If set, only collect for this specific tool.

    Returns:
        Dict mapping language to set of package names.
    """
    deps: dict[str, set[str]] = {}

    for tool_dir in sorted(MCP_TOOLS_DIR.iterdir()):
        if not tool_dir.is_dir():
            continue
        if tool_filter and tool_dir.name != tool_filter:
            continue

        meta_path = tool_dir / "meta.json"
        if not meta_path.exists():
            continue

        try:
            meta = json.loads(meta_path.read_text())
        except (json.JSONDecodeError, OSError):
            print(f"warning: could not read {meta_path}", file=sys.stderr)
            continue

        tool_deps = meta.get("dependencies", {})
        for lang, packages in tool_deps.items():
            if lang not in deps:
                deps[lang] = set()
            deps[lang].update(packages)

    return deps


def write_requirements(deps: dict[str, set[str]]) -> Path:
    """Write a requirements-tools.txt from collected Python dependencies.

    Args:
        deps: Dependencies dict from collect_dependencies.

    Returns:
        Path to the generated requirements file.
    """
    python_deps = sorted(deps.get("python", set()))

    lines = [
        "# Auto-generated by scripts/seed_dependencies.py",
        "# Do not edit manually — run the script to regenerate.",
        "",
    ]
    lines.extend(python_deps)
    lines.append("")

    REQUIREMENTS_PATH.write_text("\n".join(lines))
    return REQUIREMENTS_PATH


def install_dependencies(deps: dict[str, set[str]]) -> bool:
    """Install Python dependencies using pip.

    Args:
        deps: Dependencies dict from collect_dependencies.

    Returns:
        True if installation succeeded.
    """
    python_deps = sorted(deps.get("python", set()))
    if not python_deps:
        print("No Python dependencies to install.")
        return True

    print(f"Installing {len(python_deps)} packages: {', '.join(python_deps)}")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", *python_deps],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"pip install failed:\n{result.stderr}", file=sys.stderr)
        return False

    print(f"Installed {len(python_deps)} packages successfully.")
    return True


def main() -> None:
    """Entry point — collect deps, generate requirements, optionally install."""
    do_install = "--install" in sys.argv
    tool_filter = ""

    for i, arg in enumerate(sys.argv):
        if arg == "--tool" and i + 1 < len(sys.argv):
            tool_filter = sys.argv[i + 1]

    deps = collect_dependencies(tool_filter)
    python_count = len(deps.get("python", set()))

    if python_count == 0:
        print("No dependencies found.")
        return

    print(f"Found {python_count} unique Python dependencies across mcp_tools/")

    req_path = write_requirements(deps)
    print(f"Written to {req_path}")

    if do_install:
        success = install_dependencies(deps)
        sys.exit(0 if success else 1)
    else:
        print("Run with --install to install them, or use:")
        print(f"  pip install -r {req_path}")


if __name__ == "__main__":
    main()
